// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkjNceIeqk2CHx5DeLHFEIiwgEPbRrtU',
    appId: '1:110189339356:web:77880f503ef4baeeb1ca19',
    messagingSenderId: '110189339356',
    projectId: 'event-central-2b1f6',
    authDomain: 'event-central-2b1f6.firebaseapp.com',
    storageBucket: 'event-central-2b1f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcxeYuzN07Aw4YjZjECAsXjSzpQm053A',
    appId: '1:110189339356:android:10e010d8373fb155b1ca19',
    messagingSenderId: '110189339356',
    projectId: 'event-central-2b1f6',
    storageBucket: 'event-central-2b1f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2oAfCmTsIVABdBffbFRgPNM1ji0rgs9g',
    appId: '1:110189339356:ios:7c35729bdee7ad9ab1ca19',
    messagingSenderId: '110189339356',
    projectId: 'event-central-2b1f6',
    storageBucket: 'event-central-2b1f6.firebasestorage.app',
    iosBundleId: 'com.example.eventCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2oAfCmTsIVABdBffbFRgPNM1ji0rgs9g',
    appId: '1:110189339356:ios:7c35729bdee7ad9ab1ca19',
    messagingSenderId: '110189339356',
    projectId: 'event-central-2b1f6',
    storageBucket: 'event-central-2b1f6.firebasestorage.app',
    iosBundleId: 'com.example.eventCentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQkjNceIeqk2CHx5DeLHFEIiwgEPbRrtU',
    appId: '1:110189339356:web:a43ae9208a212765b1ca19',
    messagingSenderId: '110189339356',
    projectId: 'event-central-2b1f6',
    authDomain: 'event-central-2b1f6.firebaseapp.com',
    storageBucket: 'event-central-2b1f6.firebasestorage.app',
  );
}
